name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build --configuration=production

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh-keyscan -H ${{ secrets.DROPLET_IP }} >> ~/.ssh/known_hosts

      - name: Test SSH Connection
        run: |
          echo "Testing SSH connection..."
          ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=accept-new ${{ secrets.DROPLET_USER }}@${{ secrets.DROPLET_IP }} 'echo "SSH connection successful"'

      - name: Deploy to Droplet
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "dist/insightlytics-dashboard/browser/*"
          target: ${{ secrets.DEPLOY_PATH }}
          strip_components: 3
          timeout: "120s"
          command_timeout: "30m"
          debug: true
          proxy_timeout: "30s"
          use_insecure_cipher: false

      - name: Verify Deployment
        run: |
          echo "Waiting for deployment to stabilize..."
          sleep 15  # Give Caddy time to pick up new files
          for i in {1..3}; do
            if curl --fail --silent --head ${{ secrets.DEPLOY_URL }}; then
              echo "Deployment verified successfully!"
              exit 0
            fi
            echo "Attempt $i failed, retrying..."
            sleep 10
          done
          echo "Deployment verification failed"
          exit 1
